create table WJJ_HDICT_ROLE
(
    ROLE_ID    VARCHAR(20),
    ROLE_NAME  VARCHAR(30),
    ROLE_MENUS VARCHAR(200)
)


comment 'hdict角色信息';


INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict018', '铁通仓管', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict001', '网格人员', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict002', 'HDICT装维', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict003', '家客经理-县市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict004', '家客经理-地市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict005', 'HDICT专员-县市铁通', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict006', 'HDICT专员-县市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict007', 'HDICT专员-地市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict008', '家宽主管-县市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict009', '家宽主管-地市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict010', '市场部经理-县市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict011', '市场分管副总-县市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict012', '市场分管副总-地市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict013', '网络HDICT管理员-县市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict014', '网络全业务主管-县市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict015', '网络全业务主管-地市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict016', '网络分管副总-地市', null);
INSERT INTO WJJ_HDICT_ROLE (ROLE_ID, ROLE_NAME, ROLE_MENUS) VALUES ('hdict017', '网络家客产品支撑-地市', null);