create table WJJ_HDICT_EXPL_POSITION
(
    EXPL_POSITION_ID    VARCHAR(20),
    POSITION_ID         VARCHAR(20),
    POSITION_NAME       VARCHAR(20),
    IS_NORMAL_MJ        VARCHAR(20),
    IS_CHANGE_MJ        VARCHAR(20),
    MENJING_TYPE        VARCHAR(20),
    IS_NEW_PILLAR_MJ    VARCHAR(20),
    IS_NEW_BUTTON_MJ    VARCHAR(20),
    IS_NEW_PILANDBUT_MJ VARCHAR(20),
    QDWZ_DETAIL         VARCHAR(200),
    DISTANCE            VARCHAR(20),
    IS_NEW_KUANDAI      VARCHAR(20),
    CREATE_USER         VARCHAR(20),
    CREATE_DATE         DATE
)


comment 'HDICT预勘申请点位列表';
/

INSERT INTO WJJ_HDICT_EXPL_POSITION (EXPL_POSITION_ID, POSITION_ID, POSITION_NAME, IS_NORMAL_MJ, IS_CHANGE_MJ, MENJING_TYPE, IS_NEW_PILLAR_MJ, IS_NEW_BUTTON_MJ, IS_NEW_PILANDBUT_MJ, QDWZ_DETAIL, DISTANCE, IS_NEW_KUANDAI, CREATE_USER, CREATE_DATE) VALUES ('1', '2', '1', '2', null, null, null, null, null, null, null, null, null, null);