create table WJJ_HDICT_STUFF
(
    STUFF_ID       VARCHAR(50),
    STUFF_PROPERTY VARCHAR(50),
    STUFF_TYPE     VARCHAR(50),
    STUFF_BRAND    VARCHAR(50),
    STUFF_NAME     VARCHAR(50),
    STUFF_MODEL    VARCHAR(50),
    STUFF_PRICE    VARCHAR(50),
    STUFF_NUMS_JD  VARCHAR(50),
    STUFF_NUMS_WC  VARCHAR(50),
    STUFF_REMARK   VARCHAR(200)
)


comment '物料清单表';

INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('1', '智慧社区-辅材', '支架/立柱', '汉王', '立式金属支架', 'M0816-03L壁挂款', '1172', '0', null, '壁挂款');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('2', '智慧社区-辅材', '支架/立柱', '宇泛', '10寸单元机防水支架', 'Uface-ANHA006（M5A2U1-V- R22WFC配件）', '682', '48', null, '2个膨胀螺丝+铁钥匙');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('3', '智慧社区-辅材', '支架/立柱', '宇泛', '8寸单元机防水支架', 'Uface-ANHA001（M58041-0203- R23WFC配件）', '649', '38', null, '4个膨胀螺丝+塑料钥匙');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('4', '智慧社区-辅材', '支架/立柱', '宇泛', '门禁按钮立柱', '门禁按钮立柱_UNIUBI-ANHA0011', '220', '55', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('5', '智慧社区-辅材', '支架/立柱', '汉王', '壁挂立柱', '壁挂立柱', '645', '62', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('6', '智慧社区-辅材', '支架/立柱', '汉王', '闸机立柱', '闸机立柱开孔', '645', '15', null, '开孔');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('7', '智慧社区-辅材', '支架/立柱', '汉王', '闸机立柱', '闸机立柱全封闭', '645', '12', null, '全封闭');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('8', '智慧社区-主设备', '人脸机', '宇泛', '4G安卓版门禁机', 'M5A2U1-V-R22WFC', '2038', '10', '30', '立式');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('9', '智慧社区-主设备', '人脸机', '宇泛', '8寸PAD', 'M58041-0203-R23WFC壁挂款', '3300', '29', null, '壁挂版');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('10', '智慧社区-主设备', '人脸机', '宇泛', '8寸PAD', 'M58041-0203-R23WFC闸机款', '3300', '6', '1', '闸机款');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('11', '智慧社区-主设备', '人脸机', '汉王', '人脸核验终端', 'M0816壁挂款', '3645', '0', '2', '壁挂款');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('12', '智慧社区-主设备', '人脸机', '汉王', '人脸核验终端', 'M0816闸机款', '3645', '36', null, '闸机款');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('13', '智慧社区-辅材', '其他', '宇泛', '开关保护罩', '开关保护罩_PCOVER', '31', '96', null, '对应的开关按钮是UNIUBI-SWPB0004');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('14', '智慧社区-辅材', '灵性锁', '电机锁', '智能灵性锁', 'SC-01', '215', '5', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('15', '智慧社区-辅材', '灵性锁', '电机锁', '智能灵性锁', 'SC-01带状态', '237', '5', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('16', '智慧社区-辅材', '开关按钮', '宇泛', '开关按钮', 'UNIUBI-SWPB0004', '39', '58', null, '对应的保护罩开关保护罩_PCOVER');
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('17', '智慧社区-辅材', '开关按钮', '宇泛', '防水开关按钮', '防水开关按钮_S886M5-W', '60', '39', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('18', '智慧社区-主设备', '简易门禁', '天波', '智能门禁控制器', 'B16A', '268', '68', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('19', '智慧社区-主设备', '简易门禁', '新大陆', '智能门禁控制器', 'NL-DLK1', '260', '5', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('20', '智慧社区-辅材', '防水罩', '宇泛', '10寸单元机防水罩', 'Uface-ANHA005（M5A2U1-V-R22WFC配件）', '207', '3', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('21', '智慧社区-辅材', '防水罩', '宇泛', '8寸单元机防水罩', 'Uface-ANHA007（M58041-0203- R23WFC配件）', '207', '15', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('22', '智慧社区-辅材', '防水罩', '宇泛', 'M58041-C闸机款防雨罩套装', 'M58041-C闸机款防雨罩套装_UNIUBI-ANHA0017', '110', '4', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('23', '智慧社区-辅材', '电源', '宇泛', '配件', '小线性电源12V_5A_Uface-POL5B003', '94', '13', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('24', '智慧社区-辅材', '磁力锁', '宇泛', '280KG单门高端磁力锁_带信号', '280KG单门高端磁力锁_带信号_UNIUBI-LOAY1004', '94', '18', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('25', '智慧社区-辅材', '磁力锁', '宇泛', '280KG双门高端磁力锁_带信号', '280KG双门高端磁力锁_带信号_UNIUBI-LOAY2004', '259', '8', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('26', '智慧社区-辅材', '闭门器', '宇泛', '配件', '大号闭门器_UNIUBI-ANB00002', '138', '26', null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('27', '智慧社区-辅材', '其他', null, '电源线', null, null, null, null, null);
INSERT INTO WJJ_HDICT_STUFF (STUFF_ID, STUFF_PROPERTY, STUFF_TYPE, STUFF_BRAND, STUFF_NAME, STUFF_MODEL, STUFF_PRICE, STUFF_NUMS_JD, STUFF_NUMS_WC, STUFF_REMARK) VALUES ('28', '智慧社区-辅材', '其他', null, '网线', null, null, null, null, null);