create table WJJ_HDICT_ACCEPTANCE
(
    EXPL_REQ_ID     VARCHAR(20),
    PLAN_ID         VARCHAR(20),
    ACCEPTANCE_ID   VARCHAR(20),
    ACCEPTANCE_MAN  VARCHAR(20),
    ACCEPTANCE_DATE DATE,
    REMARK          VARCHAR(20),
    ACCEPT_TREATY   VARCHAR(30),
    ACCEPT_CONTRACT VARCHAR(30)
)

comment 'HDICT验收信息表'
;
